name: Build and Sync

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
        
      - name: Run tests
        run: npm test
        
      - name: Build project
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: dist/
          retention-days: 7

  sync:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout public via SSH
      - name: Checkout Public
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: false

      # 2. Start ssh-agent
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Clone private into ./private
      - name: Clone Private
        run: |
          git clone git@github.com:fabisev/private-repo.git private
          cd private
          git checkout -b main || git checkout main

      # 4. Mirror **from** workspace root **into** private repo root
      - name: Rsync Public → Private
        working-directory: private
        run: |
          rsync -av --delete ../ ./ \
            --exclude .git \
            --exclude private \
            --exclude .github

      # 5. Commit & push only inside private
      - name: Commit & Push
        working-directory: private
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from public at ${{ github.sha }}" || echo "Nothing to commit"
          git push --set-upstream origin main