name: Sync to Private

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. Start ssh-agent & load the SSH_PRIVATE_KEY secret
      - name: Set up SSH key
        uses: actions/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 2. Checkout the public repo (will use the loaded agent)
      - name: Checkout Public
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 3. Clone private into ./private (via ssh-agent)
      - name: Clone Private
        run: |
          git clone git@github.com:fabisev/private-repo.git private
          cd private
          git checkout -b main || git checkout main

      # 4. Rsync into the private repo root
      - name: Rsync Public → Private
        working-directory: private
        run: |
          rsync -av --delete ../ ./ \
            --exclude .git \
            --exclude private

      # 5. Commit & push inside private
      - name: Commit & Push
        working-directory: private
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from public at ${{ github.sha }}" || echo "Nothing to commit"
          git push --set-upstream origin main
