name: Sync to Private

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the public repo via SSH
      - name: Checkout Public Repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: false

      # 2. Start ssh-agent & load your key
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Clone the private repo via SSH
      - name: Clone Private Repo
        run: |
          git clone git@github.com:fabisev/private-repo.git private
          cd private
          # ensure we're on main
          git checkout main

      # 4. Mirror public → private
      - name: Mirror files into private
        run: |
          rsync -av --delete ./. private/ --exclude .git
          cd private
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from public at ${{ github.sha }}" || echo "Nothing to commit"

      # 5. Push the changes
      - name: Push to Private
        run: |
          cd private
          git push origin main
